"""empty message

Revision ID: 21491d85af5f
Revises: cb2b649a0564
Create Date: 2022-04-30 16:53:58.475955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21491d85af5f'
down_revision = 'cb2b649a0564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_attending_event',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.alter_column('users_in_groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_in_groups', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_in_groups', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_in_groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('users_attending_event')
    # ### end Alembic commands ###
